In [4]:
import tensorflow as tf
import tensorflow.keras.layers as layers
import gym
import numpy as np

In [2]:
env = gym.make('CartPole-v0')

model = tf.keras.Sequential()
model.add(layers.Dense(32,input_shape=(4,)))
model.add(layers.Dense(2, activation='sigmoid'))

loss = tf.keras.losses.MeanSquaredError()
opt = tf.keras.optimizers.Adam()

In [11]:
e = 0.9
s = env.reset()
s = np.array(s)
alpha = 0.7
discount = 0.7
for _ in range(10000):
    env.render()
    with tf.GradientTape() as tape:
        q = model(s[None,:])

        if np.random.rand() < e:
            a = np.random.randint(low=0, high=env.action_space.n)
        else:
            a = tf.argmax(tf.squeeze(q)).numpy()
            print(q)
            
        print(a)

        s,r,d,i = env.step(a)
        q_pred = q[None,0,a]

        q_true = 

        q_true =  np.array(r)
        loss_val = loss(q_true,q_pred)
        grads = tape.gradient(loss_val,model.trainable_weights)
        opt.apply_gradients(zip(grads, model.trainable_weights))

        e *= 0.9995

    if d: 
        s = numpy.array(env.reset())

0.99741733 0.9962901 ]], shape=(1, 2), dtype=float32)
0
tf.Tensor([[0.99789953 0.99644166]], shape=(1, 2), dtype=float32)
0
tf.Tensor([[0.9982888 0.996581 ]], shape=(1, 2), dtype=float32)
0
tf.Tensor([[0.9986039  0.99670666]], shape=(1, 2), dtype=float32)
0
1
tf.Tensor([[0.99858725 0.99666756]], shape=(1, 2), dtype=float32)
0
tf.Tensor([[0.99884796 0.99676526]], shape=(1, 2), dtype=float32)
0
1
tf.Tensor([[0.9988354 0.9966673]], shape=(1, 2), dtype=float32)
0
tf.Tensor([[0.99905056 0.9967338 ]], shape=(1, 2), dtype=float32)
0
tf.Tensor([[0.9992249 0.9967842]], shape=(1, 2), dtype=float32)
0
0
tf.Tensor([[0.9972114  0.99600035]], shape=(1, 2), dtype=float32)
0
tf.Tensor([[0.9977316 0.9961563]], shape=(1, 2), dtype=float32)
0
tf.Tensor([[0.9981516  0.99629873]], shape=(1, 2), dtype=float32)
0
tf.Tensor([[0.9984915 0.9964264]], shape=(1, 2), dtype=float32)
0
1
1
tf.Tensor([[0.99811184 0.99617434]], shape=(1, 2), dtype=float32)
0
1
tf.Tensor([[0.99810314 0.99606735]], shape=(1, 2), dtype=f

KeyboardInterrupt: 

In [10]:
e

0.8143496042026991